Repository cdk8s-team/cdk8s-plus, pull requests merged in 2022-04, with the labels that each got.

#505 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#506 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#507 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#508 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#509 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#510 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#511 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#512 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#513 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#518 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#517 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#519 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#522 feat(secret): immutable secrets
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/secret.ts
  test/secret.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#520 feat(config-map): immutable maps
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/config-map.ts
  test/__snapshots__/config-map.test.ts.snap
  test/config-map.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#516 feat(pod): docker registry auth
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/pod.ts
  test/pod.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#521 feat(deployment): upgrade strategy
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/deployment.ts
  test/__snapshots__/deployment.test.ts.snap
  test/deployment.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#498 chore: automatic backport
  .gitattributes
  .github/workflows/backport.yml
  .gitignore
  .projen/files.json
  .projenrc.js
  CONTRIBUTING.md
Labels: backport k8s-21/main, backport k8s-20/main

#499 feat(volume): azure, gce and aws volumes
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/pv.ts
  src/volume.ts
  test/volume.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#523 feat(stateful-set): update strategy
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/statefulset.ts
  test/statefulset.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#504 feat(daemon-set): introduce L2
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/daemon-set.ts
  src/index.ts
  test/__snapshots__/daemon-set.test.ts.snap
  test/daemon-set.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#526 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#525 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#527 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#528 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#529 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#530 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#533 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#532 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#534 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#535 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#536 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#537 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#538 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#539 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#540 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#543 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#542 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#541 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#545 chore(backport): setup hooks
  .github/workflows/backport.yml
  .projenrc.js
Labels: backport k8s-21/main, backport k8s-20/main

#547 chore(backport): remove refs from checkout since the branch is deleted
  .github/workflows/backport.yml
  .projenrc.js
Labels: backport k8s-21/main, backport k8s-20/main

#548 chore: testing backport
  CODE_OF_CONDUCT.md
Labels: backport k8s-21/main, backport k8s-20/main

#552 chore: backport test
  NOTICE
Labels: backport k8s-21/main, backport k8s-20/main

#555 chore: revert test changes
  CODE_OF_CONDUCT.md
  NOTICE
Labels: backport k8s-21/main, backport k8s-20/main

#559 chore: add OWNERS.md (#436)
  OWNERS.md
Labels: auto-approve

#579 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#580 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#581 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#606 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#607 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#608 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#609 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#610 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#611 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#612 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#613 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#614 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#616 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#615 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#617 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#618 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#619 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#620 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#622 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#623 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#621 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#624 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#625 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#626 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#627 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#628 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#629 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#630 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#631 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#632 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#633 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#634 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#635 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#497 feat(pod): pod dns settings
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/statefulset.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/pod.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#638 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#639 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#640 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#605 chore: backport tasks
  .backportrc.json
  .gitattributes
  .github/workflows/backport.yml
  .gitignore
  .projen/files.json
  .projen/tasks.json
  .projenrc.js
  docs/java.md
  docs/python.md
  docs/typescript.md
  package.json
  src/base.ts
  src/config-map.ts
  src/container.ts
  src/daemon-set.ts
  src/deployment.ts
  src/handler.ts
  src/ingress.ts
  src/job.ts
  src/pod.ts
  src/probe.ts
  src/pv.ts
  src/pvc.ts
  src/secret.ts
  src/service-account.ts
  src/service.ts
  src/statefulset.ts
  src/volume.ts
Labels: backport k8s-21/main, backport k8s-20/main

#641 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#642 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#643 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#514 chore: refactor workloads
  src/daemon-set.ts
  src/deployment.ts
  src/index.ts
  src/ingress.ts
  src/job.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/daemon-set.test.ts.snap
  test/daemon-set.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#515 feat(deployment): `minReadySeconds` and `progressDeadlineSeconds`
  src/deployment.ts
  test/__snapshots__/deployment.test.ts.snap
  test/deployment.test.ts
Labels: backport k8s-21/main, backport k8s-20/main

#651 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#652 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#653 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#655 chore: fix backport workflow
  .backportrc.json
  .github/workflows/backport.yml
  .projen/tasks.json
  .projenrc.js
  package.json
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#656 chore: fix backport workflow (#655)
  .backportrc.json
  .github/workflows/backport.yml
  .projen/tasks.json
  .projenrc.js
  package.json
Labels: auto-approve

#657 chore: fix backport workflow (#655)
  .backportrc.json
  .github/workflows/backport.yml
  .projen/tasks.json
  .projenrc.js
  package.json
Labels: auto-approve

#658 feat: opt out of service accounts auto mounting tokens
  src/pod.ts
  src/service-account.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/pod.test.ts
  test/secret.test.ts
  test/service-account.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#661 feat: opt out of service accounts auto mounting tokens (#658)
  src/pod.ts
  src/service-account.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/pod.test.ts
  test/secret.test.ts
  test/service-account.test.ts
Labels: auto-approve

#662 feat: opt out of service accounts auto mounting tokens (#658)
  src/pod.ts
  src/service-account.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/pod.test.ts
  test/secret.test.ts
  test/service-account.test.ts
Labels: auto-approve

#659 feat(stateful-set): `minReady` support
  src/stateful-set.ts
  test/statefulset.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#660 feat(workload): expression selectors and pod metadata integration
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/service.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/service.test.ts
  test/statefulset.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#665 feat(workload): expression selectors and pod metadata integration (#660)
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/service.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/service.test.ts
  test/statefulset.test.ts
Labels: auto-approve

#666 feat(workload): expression selectors and pod metadata integration (#660)
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/service.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/service.test.ts
  test/statefulset.test.ts
Labels: auto-approve

#667 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#668 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#669 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#670 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#671 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#672 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#674 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#675 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#673 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve
