Repository cdk8s-team/cdk8s-plus, pull requests merged in 2022-10, with the labels that each got.

#1211 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.24.yml
  .npmignore
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#1212 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.22.yml
  .npmignore
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#1213 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.23.yml
  .npmignore
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#1214 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1215 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1216 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1217 chore(deps): upgrade dependencies
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/release-k8s.24.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#1218 chore(deps): upgrade dependencies
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/release-k8s.22.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#1219 chore(deps): upgrade dependencies
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/release-k8s.23.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#1220 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1221 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1222 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1225 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1226 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1227 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1229 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1230 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1231 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1234 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1235 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1236 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1237 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1238 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1239 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1240 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1241 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1242 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1244 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1245 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1246 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1224 chore(docs/plus): move cdk8s+ docs to cdk8s-plus repo
  docs/plus/config-map.md
  docs/plus/container.md
  docs/plus/cronjob.md
  docs/plus/deployment.md
  docs/plus/index.md
  docs/plus/ingress.md
  docs/plus/job.md
  docs/plus/namespace.md
  docs/plus/network-policy.md
  docs/plus/pod.md
  docs/plus/pv.md
  docs/plus/pvc.md
  docs/plus/secret.md
  docs/plus/service-account.md
  docs/plus/service.md
  docs/plus/volume.md
Labels: documentation

#1233 chore: update cdk8s+ docs with v25 changes
  docs/plus/config-map.md
  docs/plus/container.md
  docs/plus/cronjob.md
  docs/plus/deployment.md
  docs/plus/index.md
  docs/plus/ingress.md
  docs/plus/job.md
  docs/plus/namespace.md
  docs/plus/network-policy.md
  docs/plus/pod.md
  docs/plus/pv.md
  docs/plus/pvc.md
  docs/plus/secret.md
  docs/plus/service-account.md
  docs/plus/service.md
  docs/plus/volume.md
Labels: documentation

#1251 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1252 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1253 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1249 chore: move v23 docs/plus from cdk8s repo
  docs/plus/config-map.md
  docs/plus/container.md
  docs/plus/cronjob.md
  docs/plus/deployment.md
  docs/plus/index.md
  docs/plus/ingress.md
  docs/plus/job.md
  docs/plus/namespace.md
  docs/plus/network-policy.md
  docs/plus/pod.md
  docs/plus/pv.md
  docs/plus/pvc.md
  docs/plus/secret.md
  docs/plus/service-account.md
  docs/plus/service.md
  docs/plus/volume.md
Labels: documentation

#1248 chore: move v24 docs/plus from cdk8s repo
  docs/plus/config-map.md
  docs/plus/container.md
  docs/plus/cronjob.md
  docs/plus/deployment.md
  docs/plus/index.md
  docs/plus/ingress.md
  docs/plus/job.md
  docs/plus/namespace.md
  docs/plus/network-policy.md
  docs/plus/pod.md
  docs/plus/pv.md
  docs/plus/pvc.md
  docs/plus/secret.md
  docs/plus/service-account.md
  docs/plus/service.md
  docs/plus/volume.md
Labels: documentation

#1254 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1255 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1256 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1257 fix: links and other cleanup in v22 docs
  docs/plus/index.md
  docs/plus/pv.md
Labels: documentation

#1258 fix: links and other cleanup in v23 docs
  docs/plus/index.md
Labels: documentation

#1259 fix: links and other cleanup in v24 docs
  docs/plus/index.md
Labels: documentation

#1260 chore(deps): upgrade dependencies
  .github/workflows/release-k8s.24.yml
  package.json
  yarn.lock
Labels: auto-approve

#1261 chore(deps): upgrade dependencies
  .github/workflows/release-k8s.22.yml
  package.json
  yarn.lock
Labels: auto-approve

#1262 chore(deps): upgrade dependencies
  .github/workflows/release-k8s.23.yml
  package.json
  yarn.lock
Labels: auto-approve

#1263 chore(deps): upgrade dependencies
  .github/workflows/release-k8s.25.yml
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1264 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1265 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1266 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1267 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1268 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1270 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1269 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1271 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1272 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1273 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1274 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1275 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1276 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1277 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1278 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1280 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1281 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1282 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1283 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1177 feat(pod): isolate pod of all network connections
  src/cron-job.ts
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
  test/cron-job.test.ts
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/job.test.ts
  test/pod.test.ts
  test/statefulset.test.ts
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main, backport-to-k8s-24/main

#1285 feat(pod): isolate pod of all network connections (#1177)
  src/cron-job.ts
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
  test/cron-job.test.ts
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/job.test.ts
  test/pod.test.ts
  test/statefulset.test.ts
Labels: auto-approve

#1286 feat(pod): isolate pod of all network connections (#1177)
  src/cron-job.ts
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
  test/cron-job.test.ts
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/job.test.ts
  test/pod.test.ts
  test/statefulset.test.ts
Labels: auto-approve

#1284 feat(pod): isolate pod of all network connections (#1177)
  src/cron-job.ts
  src/daemon-set.ts
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
  test/cron-job.test.ts
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/job.test.ts
  test/pod.test.ts
  test/statefulset.test.ts
Labels: auto-approve

#1287 chore(docs): wrong variable name
  docs/plus/job.md
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main, backport-to-k8s-24/main

#1290 chore(docs): wrong variable name (#1287)
  docs/plus/job.md
Labels: auto-approve

#1291 chore(docs): wrong variable name (#1287)
  docs/plus/job.md
Labels: auto-approve

#1223 feat(stateful-set): `service` is now optional
  src/service.ts
  src/stateful-set.ts
  test/__snapshots__/statefulset.test.ts.snap
  test/statefulset.test.ts
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1292 feat(stateful-set): `service` is now optional (#1223)
  src/service.ts
  src/stateful-set.ts
  test/__snapshots__/statefulset.test.ts.snap
  test/statefulset.test.ts
Labels: auto-approve

#1293 feat(stateful-set): `service` is now optional (#1223)
  src/service.ts
  src/stateful-set.ts
  test/__snapshots__/statefulset.test.ts.snap
  test/statefulset.test.ts
Labels: auto-approve

#1295 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1296 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1297 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1298 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1294 chore: remove v1.22.0
  .gitattributes
  .github/workflows/upgrade-k8s-22-main.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  CONTRIBUTING.md
  README.md
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1174 feat(horizontal-pod-autoscaler): Introduce `HorizontalPodAutoscaler` construct
  docs/plus/horizontal-pod-autoscaler.md
  src/deployment.ts
  src/horizontal-pod-autoscaler.ts
  src/index.ts
  src/stateful-set.ts
  test/__snapshots__/horizontal-pod-autoscaler.test.ts.snap
  test/horizontal-pod-autoscaler.test.ts
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1299 feat(horizontal-pod-autoscaler): Introduce `HorizontalPodAutoscaler` construct (#1174)
  docs/plus/horizontal-pod-autoscaler.md
  src/deployment.ts
  src/horizontal-pod-autoscaler.ts
  src/index.ts
  src/stateful-set.ts
  test/__snapshots__/horizontal-pod-autoscaler.test.ts.snap
  test/horizontal-pod-autoscaler.test.ts
Labels: auto-approve

#1300 feat(horizontal-pod-autoscaler): Introduce `HorizontalPodAutoscaler` construct (#1174)
  docs/plus/horizontal-pod-autoscaler.md
  src/deployment.ts
  src/horizontal-pod-autoscaler.ts
  src/index.ts
  src/stateful-set.ts
  test/__snapshots__/horizontal-pod-autoscaler.test.ts.snap
  test/horizontal-pod-autoscaler.test.ts
Labels: auto-approve

#1301 chore: remove `index.md` from docs
  docs/plus/index.md
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1302 chore: remove v1.22.0 (#1294)
  .projenrc.ts
  CONTRIBUTING.md
  README.md
  docs/plus/horizontal-pod-autoscaler.md
Labels: auto-approve

#1303 chore: remove v1.22.0 (#1294)
  .projenrc.ts
  CONTRIBUTING.md
  README.md
  docs/plus/horizontal-pod-autoscaler.md
Labels: auto-approve

#1304 chore: remove index.md from docs (#1301)
  docs/plus/index.md
Labels: auto-approve

#1306 fix: broken `src` imports
  src/horizontal-pod-autoscaler.ts
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1308 fix: broken src imports (#1306)
  src/horizontal-pod-autoscaler.ts
Labels: auto-approve

#1307 fix: broken src imports (#1306)
  src/horizontal-pod-autoscaler.ts
Labels: auto-approve

#1311 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1312 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1313 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1309 chore(website): `RBAC` documentation to cdk8s-plus
  docs/plus/rbac.md
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1315 chore(website): `RBAC` documentation to cdk8s-plus (#1309)
  docs/plus/rbac.md
Labels: auto-approve

#1314 chore(website): `RBAC` documentation to cdk8s-plus (#1309)
  docs/plus/rbac.md
Labels: auto-approve

#1316 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1317 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1318 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1319 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1320 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1321 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1322 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1323 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1324 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1310 feat: `v2.0.0`
  .github/workflows/release-k8s.25.yml
  .projen/tasks.json
  .projenrc.ts
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1325 feat: `v2.0.0` (#1310)
  .github/workflows/release-k8s.24.yml
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#1326 feat: `v2.0.0` (#1310)
  .github/workflows/release-k8s.23.yml
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#1327 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.24.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#1328 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.23.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#1329 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.25.yml
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  .github/workflows/upgrade-k8s-25-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#1331 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.24.yml
  package.json
  yarn.lock
Labels: auto-approve

#1332 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.23.yml
  package.json
  yarn.lock
Labels: auto-approve

#1335 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1336 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1333 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release-k8s.25.yml
  package.json
  yarn.lock
Labels: auto-approve

#1337 fix(config-map): update examples in documentation (#1334)
  docs/plus/config-map.md
Labels: auto-approve

#1340 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1341 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1342 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1343 fix(docs): incorrect API reference link in HPA overview
  docs/plus/horizontal-pod-autoscaler.md
Labels: documentation, backport-to-k8s-23/main, backport-to-k8s-24/main

#1346 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1347 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1348 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1349 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1350 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1351 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1352 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1353 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1354 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1344 chore: backport #1330 #1343 to v23 branch
  README.md
  docs/plus/horizontal-pod-autoscaler.md
Labels: documentation

#1345 chore: backport #1330 #1343 to v24 branch
  README.md
  docs/plus/horizontal-pod-autoscaler.md
Labels: documentation
