Repository cdk8s-team/cdk8s-plus, pull requests merged in 2022-03, with the labels that each got.

#392 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#391 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#393 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#395 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#396 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#397 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#398 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#399 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#400 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#401 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#402 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#383 feat: TCP socket probes
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/probe.ts
  test/probe.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#324 chore: remove unneeded k8s version references
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/config-map.ts
  src/container.ts
Labels: documentation, pr/backport-to-21, pr/backport-to-20

#404 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#403 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#405 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#407 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#406 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#408 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#410 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#409 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#411 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#390 feat: Container resource requirements and HPA
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/container.ts
  test/container.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#415 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#416 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#417 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#420 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#421 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#422 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#430 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#429 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#431 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#435 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#437 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#438 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#439 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#441 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#440 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#442 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#444 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#443 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#445 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#448 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#449 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#450 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#451 feat: init containers
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/statefulset.ts
  test/__snapshots__/deployment.test.ts.snap
  test/pod.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#453 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#452 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#454 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#457 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#456 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#458 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#455 feat: security context
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/container.ts
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/statefulset.ts
  test/__snapshots__/deployment.test.ts.snap
  test/container.test.ts
  test/pod.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#460 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/stale.yml
  .gitignore
  .projen/files.json
  package.json
  yarn.lock
Labels: auto-approve

#459 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/stale.yml
  .gitignore
  .projen/files.json
  package.json
  yarn.lock
Labels: auto-approve

#461 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/stale.yml
  .gitignore
  .projen/files.json
  package.json
  yarn.lock
Labels: auto-approve

#466 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#468 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#467 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#471 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#470 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#472 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#475 chore(deps): upgrade dependencies
  .gitignore
  package.json
  yarn.lock
Labels: auto-approve

#474 chore(deps): upgrade dependencies
  .gitignore
  package.json
  yarn.lock
Labels: auto-approve

#476 chore(deps): upgrade dependencies
  .gitignore
  package.json
  yarn.lock
Labels: auto-approve

#477 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#478 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#479 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#469 feat: pod host aliases
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/deployment.ts
  src/job.ts
  src/pod.ts
  src/statefulset.ts
  test/__snapshots__/deployment.test.ts.snap
  test/pod.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#480 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#481 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#482 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#486 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#485 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#487 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#484 feat: container lifecycle hooks
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/_action.ts
  src/container.ts
  src/handler.ts
  src/index.ts
  src/probe.ts
  test/container.test.ts
  test/handler.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#488 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#489 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#490 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#473 feat: classes for common secret types
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/secret.ts
  test/secret.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#436 chore: add OWNERS.md
  OWNERS.md
Labels: pr/backport-to-21, pr/backport-to-20

#483 feat: pv & pvc
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/index.ts
  src/pv.ts
  src/pvc.ts
  src/volume.ts
  test/__snapshots__/pv.test.ts.snap
  test/__snapshots__/pvc.test.ts.snap
  test/pv.test.ts
  test/pvc.test.ts
  test/volume.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#491 feat(pv): directly mount to container
  docs/java.md
  docs/python.md
  docs/typescript.md
  src/container.ts
  src/pv.ts
  src/volume.ts
  test/__snapshots__/container.test.ts.snap
  test/container.test.ts
  test/volume.test.ts
Labels: pr/backport-to-21, pr/backport-to-20

#494 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#495 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#496 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#500 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#501 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#502 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
