Repository cdk8s-team/cdk8s-plus, pull requests merged in 2022-05, with the labels that each got.

#679 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#680 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#682 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#683 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#681 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#432 feat: `Role`, `ClusterRole`, `RoleBinding`, `ClusterRoleBinding` L2s
  .eslintrc.json
  .gitattributes
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  api-resources.txt
  package.json
  projenrc/gen-api-resource.ts
  src/api-resource.generated.ts
  src/base.ts
  src/config-map.ts
  src/container.ts
  src/daemon-set.ts
  src/deployment.ts
  src/index.ts
  src/ingress.ts
  src/job.ts
  src/pod.ts
  src/pv.ts
  src/pvc.ts
  src/role-binding.ts
  src/role.ts
  src/secret.ts
  src/service-account.ts
  src/service.ts
  src/stateful-set.ts
  src/utils.ts
  test/base.test.ts
  test/pv.test.ts
  test/role-binding.test.ts
  test/role.test.ts
  tsconfig.dev.json
  yarn.lock
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#685 feat: `Role`, `ClusterRole`, `RoleBinding`, `ClusterRoleBinding` L2s (#432)
  .eslintrc.json
  .gitattributes
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  api-resources.txt
  package.json
  projenrc/gen-api-resource.ts
  src/api-resource.generated.ts
  src/base.ts
  src/config-map.ts
  src/container.ts
  src/daemon-set.ts
  src/deployment.ts
  src/index.ts
  src/ingress-v1beta1.ts
  src/job.ts
  src/pod.ts
  src/pv.ts
  src/pvc.ts
  src/role-binding.ts
  src/role.ts
  src/secret.ts
  src/service-account.ts
  src/service.ts
  src/stateful-set.ts
  src/utils.ts
  test/base.test.ts
  test/pv.test.ts
  test/role-binding.test.ts
  test/role.test.ts
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve

#686 feat: `Role`, `ClusterRole`, `RoleBinding`, `ClusterRoleBinding` L2s (#432)
  .eslintrc.json
  .gitattributes
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  api-resources.txt
  package.json
  projenrc/gen-api-resource.ts
  src/api-resource.generated.ts
  src/base.ts
  src/config-map.ts
  src/container.ts
  src/daemon-set.ts
  src/deployment.ts
  src/index.ts
  src/ingress-v1beta1.ts
  src/job.ts
  src/pod.ts
  src/pv.ts
  src/pvc.ts
  src/role-binding.ts
  src/role.ts
  src/secret.ts
  src/service-account.ts
  src/service.ts
  src/stateful-set.ts
  src/utils.ts
  test/base.test.ts
  test/pv.test.ts
  test/role-binding.test.ts
  test/role.test.ts
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve

#687 feat(ingress): resource backend
  src/ingress.ts
  test/ingress.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#691 feat(ingress): resource backend (#687)
  src/ingress-v1beta1.ts
  test/ingress-v1beta1.test.ts
Labels: auto-approve

#690 feat(ingress): resource backend (#687)
  src/ingress-v1beta1.ts
  test/ingress-v1beta1.test.ts
Labels: auto-approve

#688 feat(container): populate env from `ConfigMap` and `Secret`
  src/container.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/container.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#693 feat(container): populate env from `ConfigMap` and `Secret` (#688)
  src/container.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/container.test.ts
Labels: auto-approve

#692 feat(container): populate env from `ConfigMap` and `Secret` (#688)
  src/container.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/container.test.ts
Labels: auto-approve

#696 feat: bump cdk8s to version `2.x`
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/ingress.ts
  yarn.lock
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#695 chore: clean backport
  .backportrc.json
  .gitignore
  .projen/tasks.json
  .projenrc.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#701 feat: bump minimum node version to 14.x (#697)
  .github/workflows/build.yml
  .github/workflows/release-k8s.20.yml
  .github/workflows/upgrade-k8s-20-main.yml
  .github/workflows/upgrade-k8s-21-main.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve

#700 feat: bump minimum node version to 14.x (#697)
  .github/workflows/build.yml
  .github/workflows/release-k8s.21.yml
  .github/workflows/upgrade-k8s-20-main.yml
  .github/workflows/upgrade-k8s-21-main.yml
  .github/workflows/upgrade-k8s-22-main.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve

#699 feat: bump cdk8s to version `2.x` (#696)
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/ingress-v1beta1.ts
  yarn.lock
Labels: auto-approve

#698 feat: bump cdk8s to version `2.x` (#696)
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/ingress-v1beta1.ts
  yarn.lock
Labels: auto-approve

#702 chore: clean backport (#695)
  .backportrc.json
  .gitignore
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#703 chore: clean backport (#695)
  .backportrc.json
  .gitignore
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#705 chore(deps): upgrade dependencies
  .eslintrc.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#706 chore(deps): upgrade dependencies
  .eslintrc.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#694 chore: cleanup empty default values
  src/container.ts
  src/deployment.ts
  src/pod.ts
  src/utils.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/container.test.ts
  test/deployment.test.ts
  test/pod.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#708 chore: cleanup empty default values (#694)
  src/container.ts
  src/deployment.ts
  src/pod.ts
  src/utils.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/container.test.ts
  test/deployment.test.ts
  test/pod.test.ts
Labels: auto-approve

#714 chore: backport git identity fails (#710)
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#713 chore: backport git identity fails (#710)
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#716 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#718 chore: configure global identity for backport
  .github/workflows/backport.yml
  .projen/tasks.json
  .projenrc.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#720 chore: configure global identity for backport (#718)
  .github/workflows/backport.yml
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#721 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#722 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#723 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#725 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#726 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#727 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#724 fix(deployment): unable to set `maxUnavailable` on a rolling update strategy
  src/deployment.ts
  test/deployment.test.ts
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#728 fix(deployment): unable to set `maxUnavailable` on a rolling update strategy (#724)
  src/deployment.ts
  test/deployment.test.ts
Labels: auto-approve

#729 fix(deployment): unable to set `maxUnavailable` on a rolling update strategy (#724)
  src/deployment.ts
  test/deployment.test.ts
Labels: auto-approve

#684 feat(pod, workload): scheduling strategy (`affinity`, `tolerations`, `nodeName`)
  .projen/deps.json
  .projenrc.ts
  .vscode/settings.json
  package.json
  src/daemon-set.ts
  src/deployment.ts
  src/index.ts
  src/namespace.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/namespace.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/namespace.test.ts
  test/pod.test.ts
  test/service.test.ts
  test/statefulset.test.ts
  yarn.lock
Labels: backport-to-k8s-21/main, backport-to-k8s-20/main

#730 feat(pod, workload): scheduling strategy (`affinity`, `tolerations`, `nodeName`) (#684)
  .projen/deps.json
  .projenrc.ts
  .vscode/settings.json
  package.json
  src/daemon-set.ts
  src/deployment.ts
  src/index.ts
  src/namespace.ts
  src/pod.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/namespace.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/daemon-set.test.ts
  test/deployment.test.ts
  test/namespace.test.ts
  test/pod.test.ts
  test/service.test.ts
  test/statefulset.test.ts
  yarn.lock
Labels: auto-approve

#732 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#733 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#734 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#735 chore: set latest spec to `1.24.0`
  .gitattributes
  .github/workflows/upgrade-k8s-24-main.yml
  .gitignore
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
Labels: backport-to-k8s-22/main

#736 chore: set latest spec to 1.24.0 (#735)
  .gitattributes
  .github/workflows/upgrade-k8s-23-main.yml
  .github/workflows/upgrade-k8s-24-main.yml
  .gitignore
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
Labels: auto-approve

#738 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#739 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#740 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#742 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#743 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#744 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#748 chore: cleanup some unintended files
  .gitignore
  .projen/deps.json
  .projenrc.ts
  .vscode/settings.json
  package.json
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main

#750 chore: cleanup some unintended files (#748)
  .gitignore
  .projen/deps.json
  .projenrc.ts
  .vscode/settings.json
  package.json
Labels: auto-approve

#749 chore: cleanup some unintended files (#748)
  .gitignore
  .projen/deps.json
  .projenrc.ts
  .vscode/settings.json
  package.json
Labels: auto-approve

#747 feat: everything is a construct
  src/base.ts
  src/config-map.ts
  src/namespace.ts
  src/pod.ts
  src/pv.ts
  src/pvc.ts
  src/role-binding.ts
  src/role.ts
  src/secret.ts
  src/service-account.ts
  src/volume.ts
  test/container.test.ts
  test/deployment.test.ts
  test/namespace.test.ts
  test/pod.test.ts
  test/pv.test.ts
  test/pvc.test.ts
  test/role-binding.test.ts
  test/secret.test.ts
  test/service-account.test.ts
  test/volume.test.ts
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main

#751 feat: everything is a construct (#747)
  src/base.ts
  src/config-map.ts
  src/namespace.ts
  src/pod.ts
  src/pv.ts
  src/pvc.ts
  src/role-binding.ts
  src/role.ts
  src/secret.ts
  src/service-account.ts
  src/volume.ts
  test/container.test.ts
  test/deployment.test.ts
  test/namespace.test.ts
  test/pod.test.ts
  test/pv.test.ts
  test/pvc.test.ts
  test/role-binding.test.ts
  test/secret.test.ts
  test/service-account.test.ts
  test/volume.test.ts
Labels: auto-approve

#752 feat: everything is a construct (#747)
  src/base.ts
  src/config-map.ts
  src/namespace.ts
  src/pod.ts
  src/pv.ts
  src/pvc.ts
  src/role-binding.ts
  src/role.ts
  src/secret.ts
  src/service-account.ts
  src/volume.ts
  test/container.test.ts
  test/deployment.test.ts
  test/namespace.test.ts
  test/pod.test.ts
  test/pv.test.ts
  test/pvc.test.ts
  test/role-binding.test.ts
  test/secret.test.ts
  test/service-account.test.ts
  test/volume.test.ts
Labels: auto-approve

#754 feat: network policies (#737)
  src/index.ts
  src/namespace.ts
  src/network-policy.ts
  src/pod.ts
  src/utils.ts
  src/workload.ts
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/network-policy.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/network-policy.test.ts
  test/pod.test.ts
Labels: auto-approve

#753 feat: network policies (#737)
  src/index.ts
  src/namespace.ts
  src/network-policy.ts
  src/pod.ts
  src/utils.ts
  src/workload.ts
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/network-policy.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/network-policy.test.ts
  test/pod.test.ts
Labels: auto-approve

#756 feat: resource grant methods
  src/base.ts
  src/pod.ts
  src/role-binding.ts
  src/role.ts
  src/service-account.ts
  test/__snapshots__/pod.test.ts.snap
  test/pod.test.ts
  test/role-binding.test.ts
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main

#758 feat: resource grant methods (#756)
  src/base.ts
  src/pod.ts
  src/role-binding.ts
  src/role.ts
  src/service-account.ts
  test/__snapshots__/pod.test.ts.snap
  test/pod.test.ts
  test/role-binding.test.ts
Labels: auto-approve

#755 feat(service): select pods by selector
  src/container.ts
  src/deployment.ts
  src/index.ts
  src/pod.ts
  src/service.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/service.test.ts.snap
  test/deployment.test.ts
  test/ingress.test.ts
  test/service.test.ts
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main

#760 feat(service): select pods by selector (#755)
  src/container.ts
  src/deployment.ts
  src/index.ts
  src/pod.ts
  src/service.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/service.test.ts.snap
  test/deployment.test.ts
  test/ingress.test.ts
  test/service.test.ts
Labels: auto-approve

#759 feat(service): select pods by selector (#755)
  src/container.ts
  src/deployment.ts
  src/index.ts
  src/pod.ts
  src/service.ts
  src/stateful-set.ts
  src/workload.ts
  test/__snapshots__/service.test.ts.snap
  test/deployment.test.ts
  test/ingress.test.ts
  test/service.test.ts
Labels: auto-approve

#761 feat: `cdk8s-plus` is now a release-candidate
  .projen/tasks.json
  .projenrc.ts
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main

#762 chore: update spec table
  README.md
Labels: backport-to-k8s-22/main, backport-to-k8s-23/main

#764 chore: update spec table (#762)
  README.md
Labels: auto-approve

#763 chore: update spec table (#762)
  README.md
Labels: auto-approve

#765 feat: `cdk8s-plus` is now a release-candidate (#761)
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#766 feat: `cdk8s-plus` is now a release-candidate (#761)
  .projen/tasks.json
  .projenrc.ts
Labels: auto-approve

#770 chore: `ts-node` 10.x (#768)
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#769 chore: `ts-node` 10.x (#768)
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#771 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#772 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#773 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
