Repository cdk8s-team/cdk8s-plus, pull requests merged in 2023-02, with the labels that each got.

#1671 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1672 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1673 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1674 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1675 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1676 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1677 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1678 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1679 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1680 chore(deps): upgrade dependencies
  package.json
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve

#1681 chore(deps): upgrade dependencies
  package.json
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve

#1682 chore(deps): upgrade dependencies
  package.json
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve

#1683 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1684 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1685 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1686 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1688 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1687 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1690 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1691 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1692 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1693 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1694 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1695 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1696 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1697 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1698 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1700 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1701 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1702 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1703 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1704 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1705 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1706 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1707 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1708 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1709 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1710 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1711 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1713 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1712 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1714 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1716 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1719 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1720 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1721 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1722 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1724 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1723 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1725 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1726 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1728 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1729 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1727 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1730 chore(deps): upgrade dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#1731 chore(deps): upgrade dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#1732 chore(deps): upgrade dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#1733 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1734 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1735 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1718 chore: update projen project type
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: backport-to-k8s-23/main, backport-to-k8s-24/main

#1737 chore: update projen project type (#1718)
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve

#1736 chore: update projen project type (#1718)
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve

#1232 chore: guide for upgrading k8s version support in cdk8s & cdk8s+
  upgrade-k8s-version.md
Labels: documentation, backport-to-k8s-23/main, backport-to-k8s-24/main

#1739 chore: guide for upgrading k8s version support in cdk8s & cdk8s+ (#1232)
  upgrade-k8s-version.md
Labels: auto-approve

#1738 chore: guide for upgrading k8s version support in cdk8s & cdk8s+ (#1232)
  upgrade-k8s-version.md
Labels: auto-approve

#1740 chore: remove badges from README
  README.md
Labels: backport-to-k8s-24/main, backport-to-k8s-25/main

#1743 chore: backport action is failing due to node version
  .github/workflows/backport.yml
  .projenrc.ts
Labels: backport-to-k8s-24/main, backport-to-k8s-25/main

#1745 chore: backport action is failing due to node version (#1743)
  .github/workflows/backport.yml
  .projenrc.ts
Labels: auto-approve

#1744 chore: backport action is failing due to node version (#1743)
  .github/workflows/backport.yml
  .projenrc.ts
Labels: auto-approve

#1746 chore(deps): upgrade dependencies
  .gitattributes
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/triage.yml
  .gitignore
  .projen/files.json
  CODE_OF_CONDUCT.md
  DCO
  SECURITY.md
  git-hooks/README.md
  git-hooks/prepare-commit-msg
  git-hooks/setup.sh
  package.json
  yarn.lock
Labels: auto-approve

#1747 chore(deps): upgrade dependencies
  .gitattributes
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/triage.yml
  .gitignore
  .projen/files.json
  CODE_OF_CONDUCT.md
  DCO
  SECURITY.md
  git-hooks/README.md
  git-hooks/prepare-commit-msg
  git-hooks/setup.sh
  package.json
  yarn.lock
Labels: auto-approve

#1748 chore(deps): upgrade dependencies
  .gitattributes
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/triage.yml
  .gitignore
  .projen/files.json
  CODE_OF_CONDUCT.md
  DCO
  SECURITY.md
  git-hooks/README.md
  git-hooks/prepare-commit-msg
  git-hooks/setup.sh
  package.json
  yarn.lock
Labels: auto-approve

#1749 chore(deps): upgrade dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#1750 chore(deps): upgrade dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#1751 chore(deps): upgrade dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#1753 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1754 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1755 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1756 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1757 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1758 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1759 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1760 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1761 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1762 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1763 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1764 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1765 chore(deps): upgrade dependencies
  .github/workflows/triage.yml
  package.json
  yarn.lock
Labels: auto-approve

#1766 chore(deps): upgrade dependencies
  .github/workflows/triage.yml
  package.json
  yarn.lock
Labels: auto-approve

#1767 chore(deps): upgrade dependencies
  .github/workflows/triage.yml
  package.json
  yarn.lock
Labels: auto-approve
