Repository cdk8s-team/cdk8s-plus, pull requests merged in 2024-04, with the labels that each got.

#3954 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3955 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3957 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3958 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3959 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3960 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3961 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3962 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3963 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3964 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3965 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3967 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3966 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3968 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3969 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3970 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3971 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3972 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3974 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3975 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3977 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3976 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3980 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3979 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3978 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3981 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3982 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3984 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3985 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3986 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3987 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3983 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3508 fix(container): allow the same port number with different protocols
  src/container.ts
  test/container.test.ts
Labels: backport-to-k8s-26/main, backport-to-k8s-27/main

#3988 fix(container): allow the same port number with different protocols (#3508)
  src/container.ts
  test/container.test.ts
Labels: auto-approve

#3989 fix(container): allow the same port number with different protocols (#3508)
  src/container.ts
  test/container.test.ts
Labels: auto-approve

#3077 fix(statefulsets): port name not included in headless service
  src/stateful-set.ts
Labels: backport-to-k8s-26/main, backport-to-k8s-27/main

#3991 fix(statefulsets): port name not included in headless service (#3077)
  src/stateful-set.ts
Labels: auto-approve

#3990 fix(statefulsets): port name not included in headless service (#3077)
  src/stateful-set.ts
Labels: auto-approve

#3992 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3993 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3994 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3995 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3997 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4000 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3999 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4001 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4002 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4003 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4004 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4006 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4005 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4007 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4008 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4009 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4012 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4011 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4010 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4013 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4014 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4016 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4017 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4018 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4019 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4021 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4020 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4022 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4023 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4024 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4025 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4026 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4027 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4029 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4031 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4032 chore(deps): upgrade configuration
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#4033 chore(deps): upgrade configuration
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#4035 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4036 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4037 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4040 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4041 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3818 feat(probe): add `host` property to HttpGet probes
  src/_action.ts
  src/probe.ts
  test/probe.test.ts
Labels: backport-to-k8s-27/main, backport-to-k8s-28/main

#4042 feat(probe): add `host` property to HttpGet probes (#3818)
  src/_action.ts
  src/probe.ts
  test/probe.test.ts
Labels: auto-approve

#4043 feat(probe): add `host` property to HttpGet probes (#3818)
  src/_action.ts
  src/probe.ts
  test/probe.test.ts
Labels: auto-approve

#3812 feat(container): support `restartPolicy` field
  src/container.ts
  src/pod.ts
  test/__snapshots__/container.test.ts.snap
  test/container.test.ts
  test/pod.test.ts
Labels: backport-to-k8s-27/main, backport-to-k8s-28/main

#3813 fix(role): use rules coming from the roleProps
  src/role.ts
  test/role.test.ts
Labels: backport-to-k8s-27/main, backport-to-k8s-28/main

#4045 feat(container): support `restartPolicy` field (#3812)
  src/container.ts
  src/pod.ts
  test/__snapshots__/container.test.ts.snap
  test/container.test.ts
  test/pod.test.ts
Labels: auto-approve

#4047 fix(role): use rules coming from the roleProps (#3813)
  src/role.ts
  test/role.test.ts
Labels: auto-approve

#4046 fix(role): use rules coming from the roleProps (#3813)
  src/role.ts
  test/role.test.ts
Labels: auto-approve

#4048 feat(container): add capabilities to security context (#3817)
  src/container.ts
  test/container.test.ts
Labels: auto-approve

#4049 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4050 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4051 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4052 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4054 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4055 feat(container): add capabilities to security context (#3817)
  src/container.ts
  test/container.test.ts
Labels: auto-approve

#4057 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4056 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4058 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4059 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4060 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4061 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4062 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4063 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4065 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4066 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4067 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4068 chore(deps): upgrade configuration
  .github/workflows/release-k8s.27.yml
  package.json
  yarn.lock
Labels: auto-approve

#4069 chore(deps): upgrade configuration
  .github/workflows/release-k8s.28.yml
  package.json
  yarn.lock
Labels: auto-approve

#4070 chore(deps): upgrade configuration
  .github/workflows/release-k8s.29.yml
  package.json
  yarn.lock
Labels: auto-approve

#4071 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4072 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4073 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4074 chore(deps): upgrade configuration
  .npmignore
  package.json
  yarn.lock
Labels: auto-approve

#4075 chore(deps): upgrade configuration
  .npmignore
  package.json
  yarn.lock
Labels: auto-approve

#4076 chore(deps): upgrade configuration
  .npmignore
  package.json
  yarn.lock
Labels: auto-approve

#4077 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4078 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4080 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4081 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4082 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#4083 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4084 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#4085 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve
