Repository cdk8s-team/cdk8s-plus, pull requests merged in 2024-02, with the labels that each got.

#3645 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3646 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3647 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3648 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3649 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3650 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3653 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3652 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3657 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3659 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3660 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3662 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3663 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3664 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3667 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3668 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3666 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3669 chore(deps): upgrade configuration
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#3670 chore(deps): upgrade configuration
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#3671 chore(deps): upgrade configuration
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#3654 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3655 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3656 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3675 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3677 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3678 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3679 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3680 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3681 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3683 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3682 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3684 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3685 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3686 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3688 chore(deps): upgrade configuration
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/release-k8s.26.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-configuration-k8s-24-main.yml
  .github/workflows/upgrade-configuration-k8s-25-main.yml
  .github/workflows/upgrade-configuration-k8s-26-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-26-main.yml
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#3687 chore(deps): upgrade configuration
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/release-k8s.25.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-23-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-configuration-k8s-23-main.yml
  .github/workflows/upgrade-configuration-k8s-24-main.yml
  .github/workflows/upgrade-configuration-k8s-25-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-23-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-23-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-25-main.yml
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#3690 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3691 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3692 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3693 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3694 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3695 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3696 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3697 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3698 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3699 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3701 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3700 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3702 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3704 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3706 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3705 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3707 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3708 chore(deps): upgrade configuration
  .github/workflows/pull-request-lint.yml
  package.json
  yarn.lock
Labels: auto-approve

#3711 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3712 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3713 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3714 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3715 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3716 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3717 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3718 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3719 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3720 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3721 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3722 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3723 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3725 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3724 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3726 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3727 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3729 chore(deps): upgrade configuration
  .github/workflows/release-k8s.25.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-23-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-configuration-k8s-23-main.yml
  .github/workflows/upgrade-configuration-k8s-24-main.yml
  .github/workflows/upgrade-configuration-k8s-25-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-23-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-23-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-25-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#3730 chore(deps): upgrade configuration
  .github/workflows/release-k8s.26.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-configuration-k8s-24-main.yml
  .github/workflows/upgrade-configuration-k8s-25-main.yml
  .github/workflows/upgrade-configuration-k8s-26-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-24-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-26-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#3731 chore(deps): upgrade configuration
  .github/workflows/release-k8s.27.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-compiler-dependencies-k8s-27-main.yml
  .github/workflows/upgrade-configuration-k8s-25-main.yml
  .github/workflows/upgrade-configuration-k8s-26-main.yml
  .github/workflows/upgrade-configuration-k8s-27-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-dev-dependencies-k8s-27-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-25-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-26-main.yml
  .github/workflows/upgrade-runtime-dependencies-k8s-27-main.yml
  package.json
  yarn.lock
Labels: auto-approve

#3732 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3733 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3734 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3737 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3736 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3738 chore(deps): upgrade configuration
  .github/workflows/release-k8s.25.yml
  package.json
  yarn.lock
Labels: auto-approve

#3739 chore(deps): upgrade configuration
  .github/workflows/release-k8s.26.yml
  package.json
  yarn.lock
Labels: auto-approve

#3740 chore(deps): upgrade configuration
  .github/workflows/release-k8s.27.yml
  package.json
  yarn.lock
Labels: auto-approve

#3743 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3744 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3745 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3746 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3747 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3748 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3749 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3750 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3753 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3754 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3755 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3756 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3757 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3758 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3759 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3760 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3761 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3762 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3763 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#2964 fix(ingress): add `ingressClassName` to `IngressProps`
  src/ingress.ts
  test/ingress.test.ts
Labels: backport-to-k8s-25/main, backport-to-k8s-26/main

#3764 fix(ingress): add `ingressClassName` to `IngressProps` (#2964)
  src/ingress.ts
  test/ingress.test.ts
Labels: auto-approve

#3765 fix(ingress): add `ingressClassName` to `IngressProps` (#2964)
  src/ingress.ts
  test/ingress.test.ts
Labels: auto-approve

#3768 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3766 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3767 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3770 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3771 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3772 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3775 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3776 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3777 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3778 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3779 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3780 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3781 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3782 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3783 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3784 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3785 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3786 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3788 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3790 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3789 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3791 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3792 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3793 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3794 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3795 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3796 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#3797 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3799 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3798 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3800 fix: npm releases failing to generate provenance
  .projenrc.ts
  package.json
Labels: backport-to-k8s-26/main, backport-to-k8s-27/main

#3802 fix: npm releases failing to generate provenance (#3800)
  .projenrc.ts
  package.json
Labels: auto-approve

#3801 fix: npm releases failing to generate provenance (#3800)
  .projenrc.ts
  package.json
Labels: auto-approve

#3803 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3804 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3805 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#3806 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3808 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3807 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#3809 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#3811 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve
