Repository cdk8s-team/cdk8s-plus, pull requests merged in 2025-02, with the labels that each got.

#5242 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5243 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5244 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5245 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5246 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5247 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5248 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5249 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5250 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5251 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5252 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5253 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5254 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5255 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5256 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5258 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5259 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5261 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5260 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5262 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5263 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5264 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5267 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5266 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5268 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5269 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5270 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5271 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5272 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5273 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5274 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5275 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5276 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5277 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5278 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5279 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5280 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5281 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5282 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5283 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5284 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5285 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5286 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5287 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5288 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5291 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5290 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5292 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5293 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5294 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5295 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5298 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5300 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5299 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5301 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5302 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5303 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5304 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5305 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5306 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5307 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5308 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5309 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5310 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5311 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5312 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5313 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5314 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5315 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5316 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5317 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5320 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5321 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5322 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5324 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5325 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5326 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5327 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5328 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5329 chore(deps): upgrade configuration
  yarn.lock
Labels: auto-approve

#5330 chore(deps): upgrade configuration
  yarn.lock
Labels: auto-approve

#5331 chore(deps): upgrade configuration
  yarn.lock
Labels: auto-approve

#5332 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5333 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5335 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5336 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5337 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5340 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5341 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5342 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5343 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5338 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5344 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5345 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5346 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5347 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5348 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5349 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5351 chore(deps): upgrade configuration
  yarn.lock
Labels: auto-approve

#5352 chore(deps): upgrade configuration
  yarn.lock
Labels: auto-approve

#5350 chore(deps): upgrade configuration
  yarn.lock
Labels: auto-approve

#4902 feat(pod): shareProcessNamespace
  src/pod.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/horizontal-pod-autoscaler.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/network-policy.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/service.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
Labels: backport-to-k8s-29/main, backport-to-k8s-30/main

#5354 feat(pod): shareProcessNamespace (backport #4902)
  src/pod.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/horizontal-pod-autoscaler.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/network-policy.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/service.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
Labels: auto-approve, backport

#5353 feat(pod): shareProcessNamespace (backport #4902)
  src/pod.ts
  test/__snapshots__/container.test.ts.snap
  test/__snapshots__/cron-job.test.ts.snap
  test/__snapshots__/daemon-set.test.ts.snap
  test/__snapshots__/deployment.test.ts.snap
  test/__snapshots__/horizontal-pod-autoscaler.test.ts.snap
  test/__snapshots__/job.test.ts.snap
  test/__snapshots__/network-policy.test.ts.snap
  test/__snapshots__/pod.test.ts.snap
  test/__snapshots__/service.test.ts.snap
  test/__snapshots__/statefulset.test.ts.snap
Labels: auto-approve, backport

#5355 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5357 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5361 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5362 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5365 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5366 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5367 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5368 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5370 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5369 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5373 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5372 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5374 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5375 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5376 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5377 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5378 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5379 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5380 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve
