Repository cdk8s-team/cdk8s-plus, pull requests merged in 2025-05, with the labels that each got.

#5672 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5673 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5674 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5675 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5677 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5678 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5679 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5680 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5682 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5683 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5684 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5685 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5686 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5688 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5689 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5690 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5691 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5692 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5694 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5695 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5696 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5697 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5699 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5700 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5701 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5702 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5703 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5681 fix(pvc): fractional gibibytes storage sizes are not allowed
  src/pvc.ts
  test/__snapshots__/pvc.test.ts.snap
  test/pvc.test.ts
Labels: backport-to-k8s-30/main, backport-to-k8s-31/main

#5707 fix(pvc): fractional gibibytes storage sizes are not allowed (backport #5681)
  src/pvc.ts
  test/__snapshots__/pvc.test.ts.snap
  test/pvc.test.ts
Labels: auto-approve, backport

#5708 fix(pvc): fractional gibibytes storage sizes are not allowed (backport #5681)
  src/pvc.ts
  test/__snapshots__/pvc.test.ts.snap
  test/pvc.test.ts
Labels: auto-approve, backport

#5710 fix: update example in Services docs to be valid (backport #5578)
  docs/plus/service.md
Labels: auto-approve, backport

#5471 feat(pod): support `enableServiceLinks`
  src/pod.ts
  test/pod.test.ts
Labels: backport-to-k8s-30/main, backport-to-k8s-31/main

#5712 feat(pod): support `enableServiceLinks` (backport #5471)
  src/pod.ts
  test/pod.test.ts
Labels: auto-approve, backport

#5711 feat(pod): support `enableServiceLinks` (backport #5471)
  src/pod.ts
  test/pod.test.ts
Labels: auto-approve, backport

#5713 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5714 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5715 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5716 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5717 chore(deps): upgrade compiler dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5719 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5720 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5722 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5723 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5724 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5721 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5725 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5726 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5727 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5728 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5729 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5730 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5731 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5732 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5734 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5735 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5736 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5737 chore(deps): upgrade dev dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#5738 chore(deps): upgrade dev dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#5739 chore(deps): upgrade dev dependencies
  package.json
  src/imports/k8s.ts
  yarn.lock
Labels: auto-approve

#5704 chore(deps): upgrade configuration
  .eslintrc.json
  package.json
  src/container.ts
  src/pod.ts
  src/probe.ts
  src/pvc.ts
  src/service.ts
  src/volume.ts
  yarn.lock
Labels: auto-approve

#5706 chore(deps): upgrade configuration
  .eslintrc.json
  package.json
  src/container.ts
  src/pod.ts
  src/probe.ts
  src/pvc.ts
  src/service.ts
  src/volume.ts
  yarn.lock
Labels: auto-approve

#5740 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5741 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5742 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5743 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5744 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5705 chore(deps): upgrade configuration
  .eslintrc.json
  package.json
  src/container.ts
  src/pod.ts
  src/probe.ts
  src/pvc.ts
  src/service.ts
  src/volume.ts
  yarn.lock
Labels: auto-approve

#5747 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5748 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5749 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5750 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5751 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5752 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5754 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5756 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#5757 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#5758 chore(deps): upgrade dev dependencies
  yarn.lock
Labels: auto-approve

#5755 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5759 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5760 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5761 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5763 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5765 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5766 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5768 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5767 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5769 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5770 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5772 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5773 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5774 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5775 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5776 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5777 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5778 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5780 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5783 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5785 chore(deps): upgrade compiler dependencies
  yarn.lock
Labels: auto-approve

#5787 chore(deps): upgrade configuration
  package.json
  yarn.lock
Labels: auto-approve

#5789 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5782 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5792 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5793 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5796 chore(deps): upgrade configuration
  .github/workflows/release-k8s.31.yml
  package.json
  yarn.lock
Labels: auto-approve

#5795 chore(deps): upgrade configuration
  .github/workflows/release-k8s.32.yml
  package.json
  yarn.lock
Labels: auto-approve

#5797 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5801 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5803 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5804 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#5805 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve
